name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '13'
      - run: yarn
      - run: yarn run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '13'
      - run: yarn
      - run: yarn run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '13'
      - run: yarn
      - run: yarn run generate
      - run: yarn run strip-scripts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  pdf:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: zenika/alpine-chrome:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - run: ci/generate-pdf.sh
      - name: Upload Dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-with-pdf
          path: dist/
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: dist/*.pdf
#  screenshot:
#    runs-on: ubuntu-latest
#    needs: build
#    container:
#      image: alekzonder/puppeteer:latest
#      options: --user root
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '16'
#      - name: Download artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: dist
#          path: dist/
#      - run: node ci/generate-screenshot.js
#      - name: Upload screenshot
#        uses: actions/upload-artifact@v4
#        with:
#          name: screenshot
#          path: dist/screenshot.png

  update_resume_json:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '13'
      - run: yarn
      - run: yarn run resume.json --github-pat ${{ secrets.SECRET_GISTS }}

  lint_resume_json:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master' || github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '13'
      - run: yarn
      - run: yarn run resume.json

  html_proofer:
    runs-on: ubuntu-latest
    needs: pdf
    container:
      image: ruby:2.7
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-with-pdf
          path: dist/
      - name: Set up Ruby
        run: |
          ruby -v
          bundle install -j $(nproc) --path vendor/ruby
      - run: ci/run-html-proofer.rb

#  pages:
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/master' && github.event_name != 'schedule'
#    steps:
#      - uses: actions/checkout@v4
#      - run: ci/pages-preparation.sh
#      - name: Upload pages
#        uses: actions/upload-artifact@v4
#        with:
#          name: public
#          path: public/
